"""create review table

Revision ID: 275991167543
Revises: 
Create Date: 2026-09-21 09:31:13.165335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '275991167543'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_score', sa.Float(), nullable=False),
    sa.Column('strengths', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weaknessess', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missing_skills', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('user_password_hash_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_password_hash_key'), 'user', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.drop_table('review')
    # ### end Alembic commands ###
